### ISSUE TITLE
Tag creation is not done properly at install (with install.sh script)

### ISSUE THREAD

**Issue by lhubert** [Hurence/historian#140]
When declaring a tag at installation (yes on do you want to create a tag ? and adding tag name "Country"), we get this error back after Solr install (on a fresh install, on Ubuntu 18.04 and a reasonable PC):

```
{ "add-field": { "name":"Country", "type":"string" } }
curl: (7) Failed to connect to localhost port 8983: Connection refused
```
This means Solr is not up and running yet probably. So do we need a ping until it is ready ?

**Comment by MiniPlayer** [comment]
After investigation this was due to the solr server that was running. When solr is run as root it stops by default. So i added the option -force so that user can run the install as root.
