### ISSUE TITLE
Import CSV not working with no explanation at all

### ISSUE THREAD

**Issue by lhubert** [Hurence/historian#145]
I used this import with attached file. I suspect the parsing of the timestamp is not okay since I used this from somehow the REST API doc but I think it is probably wrong. Seems weird to me that month and minutes have the same symbol in format_date... probably REST api doc is wrong. Still nothing is returned event not a simple message...
curl -X POST \
http://localhost:8080/api/historian/v0/import/csv \
-F 'my_csv_file=/opt/hdh/samples/happiness/2015.csv' \
-F mapping.name="Metric" \
-F mapping.value="Happiness Score" \
-F mapping.timestamp=Timestamp \
-F mapping.tags=Country \
-F timestamp_unit=MILLISECONDS_EPOCH \
-F format_date=yyyy-m-DTHH:mm+ss.SSS \
-F timezone_date=UTC

[2015.txt](https://github.com/Hurence/historian/files/4902268/2015.txt)

**Comment by MiniPlayer** [comment]
I just tested with postman and we Got a reponse, see below image
![Capture d’écran de 2020-07-16 11-45-14](https://user-images.githubusercontent.com/5628261/87657184-c1c33000-c75a-11ea-980d-42bb32f9ff78.png)

**Comment by MiniPlayer** [comment]
I just tried in prod mode and we get the error in log as well. I guess the problem come from the curl command.

**Comment by MiniPlayer** [comment]
I just tried this command that worked as expected:
```bash
curl -X POST \
  http://localhost:8080/api/historian/v0/import/csv \
  -F 'my_csv_file=@/home/gregoire/Téléchargements/2015.txt' \
  -F mapping.name=Metric \
  -F 'mapping.value=Happiness Score' \
  -F mapping.timestamp=Timestamp \
  -F timestamp_unit=MILLISECONDS_EPOCH \
  -F 'format_date=yyyy-m-DTHH:mm+ss.SSS' \
  -F timezone_date=UTC
```
I think you forgot to add the '@' for specifying the file so no file is sent. In this case it seems that an empty response is sent without error. This is indeed a bug in this case we should return an error bad request no file attached.

**Comment by MiniPlayer** [comment]
Where does your csv come frome ? The dates are like 2015-01-31T23:59:59+99:999
I am not sure to what correspond the last five numbers. the ":" separator seems to tell they mean different things.
And I am not sure this type of date format is supported by SimpleDateFormat of Java.

**Comment by MiniPlayer** [comment]
Well I changed a little the code so that if there is no file in input it sends an error with 
```json
{
  "error": "Request is not containing any files"
}
```
I case all points of csv filed to be parsed correctly you have a response like :
```json
{
  "errors":[
    {
      "file":"csv-exemple.csv",
      "cause":"There is no valid points"
    }
  ]
}
```
If you want more détail on why no point could be correctly parsed then it should be Feiz that implement this as I have difficulty to comprehend the code.

I am waiting for your response regarding the date format so that I can test it works with simple format.
