### ISSUE TITLE
script historian-server.sh does not stop nor restart properly

### ISSUE THREAD

**Issue by lhubert** [Hurence/historian#149]
after shutting down the computer, the processes are killed of course but their pid still exist. Therefore, doing a historian-server.sh start does not work. Doing a historian-server.sh stop seems to clear things up with - all killed... but doing a fresh start won't work because of Solr not started and this stack trace
java.util.concurrent.RejectedExecutionException: Task org.apache.solr.common.util.ExecutorUtil
$MDCAwareThreadPoolExecutor$$Lambda$174/0x000000084028d040@336e8a74 rejected from org.apache.s
olr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor@4ff7700e[Terminated, pool size = 0, ac
tive threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Thr
eadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:82
5)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1
355)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.execute(Executo
rUtil.java:194)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorServi
ce.java:118)
	at org.apache.solr.common.cloud.SolrZkClient$ProcessWatchWithExecutor.process(SolrZkCl
ient.java:843)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:535)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510)
15987 [vert.x-worker-thread-1-EventThread] INFO  org.apache.zookeeper.ClientCnxn$EventThread.r
un(ClientCnxn.java:524) - EventThread shut down for session: 0x0
16081 [vert.x-worker-thread-0] INFO  org.apache.zookeeper.ZooKeeper.close(ZooKeeper.java:1422)
 - Session: 0x0 closed
16082 [vert.x-worker-thread-0-EventThread] INFO  org.apache.zookeeper.ClientCnxn$EventThread.r
un(ClientCnxn.java:524) - EventThread shut down for session: 0x0
16082 [vert.x-worker-thread-0] WARN  com.hurence.webapiservice.historian.impl.SolrHistorianSer
viceImpl.pingSolrServer(SolrHistorianServiceImpl.java:174) - Could not connect so solr
16084 [vert.x-worker-thread-0] INFO  com.hurence.webapiservice.historian.impl.SolrHistorianSer
viceImpl.pingSolrServer(SolrHistorianServiceImpl.java:177) - waiting 6000 ms before retrying.

The real problem is the doc since we do not have a section explaining how to restart things and by the way; there is a paragraph but the command to start solr is wrong (wrong place for data directory).

Conclusion: the script should not only be based on pid to decide if things are running or not... also it should explicitly say that Solr has to be started first. Finally this should be better documented and the command to start Solr should be fixed.

**Comment by MiniPlayer** [comment]
I think the correct way to handle this is :
* Have a configuration file that tells if we use the standalone solr or not
  * If yes, then we handle the start and stop of this solr instance as well in historian-server.sh
Either way then we try to launch the historian, but we should be able to indicates if it succeeded or not.  If it fails we print a message that it failed explaining why if possible.

**Comment by MiniPlayer** [comment]
I feel like it is a waste of time of doing scripts for this kind of stuffs.
It would be better to use Java for install and start...
Therefore I would fix this bug by adding a java job that will start historian-server.
