### ISSUE TITLE
Automated test for install

### ISSUE THREAD

**Issue by MiniPlayer** [Hurence/historian#170]
The installation process of the historian should be tested by an automatic process. At least for these different OS :

* Mac
* Ubuntu
* CentOS 7.x
* Redhat 7.x

Unfortunately as Mac can not be run on VM or docker, this one will have to be tested manually.

**Comment by lhubert** [comment]
Not only for install... for install and inject via REST a CSV file and query to get a result. The full chain is tested.

**Comment by MiniPlayer** [comment]
The REST api is already tested with integration test. 
We also could add test after having installed the historian in standalone mode with curl commands but I think this should be done in a separate issue as this is add work.

**Comment by MiniPlayer** [comment]
I just rethink about this. As the rest api is already tested. The main thing to test after installation is that the main REST endpoints are available. Without specific requests as this is already tested in integration tests in historian build. And those main endpoints will be part of the installation test.
