### ISSUE TITLE
fix QueryEndPointFocusOnSamplingWithPreAggCurrentVersionIT test that have a methode that returns null 

### ISSUE THREAD

**Issue by FeizNouri** [Hurence/historian#182]
the class historian/historian-server/src/integration-test/java/com/hurence/webapiservice/http/api/grafana/hurence/QueryEndPointFocusOnSamplingWithPreAggCurrentVersionIT.java has a methode that returns null : 
`private static List<Chunk> buildChunks(String metric_10_chunk, List<List<Measure>> pointsByChunk10Chunks) {
        return null;
    }`

**Comment by MiniPlayer** [comment]
Uncommented class and implemented the method.
