### ISSUE TITLE
Exporting data as simple JSON/CSV/Excel formats should be possible

### ISSUE THREAD

**Issue by lhubert** [Hurence/historian#30]
A mechanism to export data should be available. Preferably through a REST API.

**Comment by MiniPlayer** [comment]
Currenlty we can query metrics via the /api/grafana/query endpoint. This is the only endpoint for querying timeseries.
Request are like that :
```json
{
  "panelId": 1,
  "range": {
    "from": "2016-10-31T06:33:44.866Z",
    "to": "2016-10-31T12:33:44.866Z",
    "raw": {
      "from": "now-6h",
      "to": "now"
    }
  },
  "rangeRaw": {
    "from": "now-6h",
    "to": "now"
  },
  "interval": "30s",
  "intervalMs": 30000,
  "targets": [
    {
      "target": "temp_a",
      "refId": "A",
      "type": "timeserie"
    },
    {
      "target": "temp_b",
      "refId": "B",
      "type": "timeserie"
    }
  ],
  "format": "json",
  "maxDataPoints": 550
}
```
And produce response with content-type 'application/json' like : 
```json
[
  {
    "target":"temp_a",
    "datapoints":[
      [622, 1477895624866],
      [-3, 1477916224866],
      [365, 1477917224866]
    ]
  },
  {
    "target":"temp_b",
    "datapoints":[
      [861, 1477895624866],
      [767, 1477917224866]
    ]
  }
]
```
The idea is to implement a second endpoint, for exemple "/export/csv" that expects exactly the same type of requests. But produce response with conten-type : "text/csv".

```csv
metric,date,value,quality,tags
temp_a,100,1.0,4.0,
temp_a,110,1.2,3.9,
temp_b,100,1.0,4.0,
```

For exemple. First implement this with default choice for everything, then user should be able to choose in request thos kind of things : 

* csv column separator
* if the header is sent or not
* if we want the quality or not...

#Requirement

The creation of CSV should be done using a specific library. For exemple you can look at this code : 
TODO

**Comment by MiniPlayer** [comment]
You could do something like that :

![Capture d’écran de 2020-03-02 17-58-29](https://user-images.githubusercontent.com/5628261/75698843-b7befa00-5caf-11ea-8cb9-54f37d8f9046.png)

But do not forget to change expected response type ! Like for grafana :
![Uploading Capture d’écran de 2020-03-02 17-59-10.png…]()
