### ISSUE TITLE
add tags into chunks

### ISSUE THREAD

**Issue by oalam** [Hurence/historian#5]
- chunk_tags field (array to be specified with gateway team)

**Comment by MiniPlayer** [comment]
The tags should be added in a separate Collection than chunks.
We called for exemple this collection "annotations".
Each particular event would be indexed in this collection in the following format :
  {
    "time": 1581075145188,
    "timeEnd": 1581075145188,
    "text": "drop of 3 detected",
    "tags": [
      "metric_1", "drop"
    ]
  }
