### ISSUE TITLE
Manage quality in chunks

### ISSUE THREAD

**Issue by lhubert** [Hurence/historian#72]
Since we now want to store the quality of data and other things, we should revisit the shunking and deal with the compression threshold.

**Comment by MiniPlayer** [comment]
SO the quality will be added, we are to decide how :
* in current "chunk_value" directly
* in a separate value "chunk_quality_value" of the same nature than "chunk_value"
This part will be decided and implemented by MiniPlayer.

Feiz you will have to implement quality management throughout the REST api : 
* import csv
* import tag
* export csv
* query

For saving quality you will use a methods to be defined by Miniplayer.

In addition to raw quality (that should be queryable), we will save in chunks : 
* quality_avg
* first_quality
That would allow an efficient filter when requesting. Here some explanation about query endpoint.

Currently a simple request is like :
```json
        {
          "from": "2016-10-31T06:33:44.866Z",
          "to": "2020-10-31T12:33:44.866Z",
          "names": ["metric_1"],
          "format": "json",
          "max_data_points": 8,
          "tags": {
              "sensor" : "sensor_1"
          },
          "sampling":{
             "algorithm": "MIN",
             "bucket_size" : 100
          }
        }
```
We should add a field quality which accepts a float value between 0.0 and 1.0
```json
        {
          "names": ["metric_1"],
          "quality" :  0.8
        }
```
this would mean for big request to filter out all chunk with a quality_avg < 0.8
Or for smaller request to filter out point with quality < 0.8

Also we should be able to indicate quality desired for each one of the different metrics.
For example.
```json
        {
          "names": [
            "metric_2",
            {
              "name": "metric_1",
               "quality" :  0.5
            }
          ],
          "quality" :  0.8
        }
```
Would request metric_2 with quality > 0.8 and metric_1 with quality > 0.5. It works the same that with tags.

Note that a reflection needs to be done on request to calcul max total number of point returned by request, 
Should you filter chunk with insufficient quality or not ?
